on: push

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.3'
          tools: codeception:3.1*

      - name: Execute tests
        run: |
          set -e
          echo "hello world"
          exit 1