on: push

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: bagisto_testing
          MYSQL_USER: bagisto
          MYSQL_PASSWORD: secret
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Verify MySQL connection from container
        run: |
          apt-get update
          apt-get install -y mysql-client
          mysql --host mysql -uroot -proot -e "SHOW DATABASES"
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.3'
          extensions: intl, curl, mbstring, openssl, pdo, pdo_mysql, tokenizer

      - name: Composer install
        run: |
          set -e
          composer global require hirak/prestissimo
          composer install --no-interaction --ansi --no-progress --no-suggest --optimize-autoloader

      - name: Migrate database
        run: |
          set -e
          php artisan migrate --env=testing

      - name: Execute tests
        run: |
          set -e
          vendor/bin/codecept run unit